### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by TofuGG** [Razorboot/LOVR-OOP-Graphics-Engine#3]
Error: lovr_graphics_engine/shaders/forward_arrays.lua:1: attempt to index global 'lovr' (a nil value)

Error: lovr_graphics_engine/shaders/forward_arrays.lua:1: attempt to index global 'lovr' (a nil value)
stack traceback:
	[love "boot.lua"]:345: in function '__index'
	lovr_graphics_engine/shaders/forward_arrays.lua:1: in main chunk
	[C]: in function 'require'
	lovr_graphics_engine/modules/scene.lua:3: in main chunk
	[C]: in function 'require'
	lovr_graphics_engine/include.lua:2: in main chunk
	[C]: in function 'require'
	main.lua:2: in main chunk
	[C]: in function 'require'
	[love "boot.lua"]:316: in function <[love "boot.lua"]:126>
	[C]: in function 'xpcall'
	[love "boot.lua"]:355: in function <[love "boot.lua"]:348>
	[C]: in function 'xpcall'

**Comment by Razorboot** [comment]
Hm, I haven't had this issue previously. Are you executing this using LOVR Nightly builds?

**Comment by TofuGG** [comment]
Sorry, looks like the error was on my end
